CREATE DATABASE IF NOT EXISTS alx_book_store;
USE alx_book_store;

--AUTHOR TABLE
CREATE TABLE IF NOT EXISTS AUTHORS (
    AUTHOR_ID INT AUTO_INCREMENT PRIMARY KEY,
    AUTHOR_NAME VARCHAR(215)
);

--BOOKS TABLE
CREATE TABLE IF NOT EXISTS BOOKS(
    BOOK_ID AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(130) NOT NULL,
    AUTHOR_ID INT NOT NULL,
    PRICE DOUBLE NOT NULL,
    PULICATION_DATE DATE,
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(AUTHOR_ID)
);

--COSTUMERS TABLE
CREATE TABLE IF NOT EXISTS CUSTOMERS(
    CUSTOMER_ID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(215) NOT NULL,
    EMAIL VARCHAR(215) NOT NULL,
    ADRESS TEXT
);

--ORDERS TABLE
CREATE TABLE IF NOT EXISTS ORDERS(
    ORDER_ID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_ID INT NOT NULL,
    ORDER_DATE DATE,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);

--ORDER_DETAIL TABLE
CREATE Table IF NOT EXISTS ORDERS_DETALS(
    orderdetailid INT AUTO_INCREAMENT PRIMARY KEY ,
    ORDER_ID INT NOT NULL,
    BOOK_ID INT NOT NULL,
    QUANTITI DOUBLE NOT NULL,
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_IS)
);
